### ISSUE TITLE
Issue encountered while running 3rd script, please help

### ISSUE THREAD

**Issue by vibhavk** [davidpraise45/face-recognition#1]
OpenCV Error: Assertion failed (!empty()) in detectMultiScale, file /io/opencv/modules/objdetect/src/cascadedetect.cpp, line 1698
Traceback (most recent call last):
  File "face_recognition.py", line 61, in <module>
    minSize=(30, 30))
cv2.error: /io/opencv/modules/objdetect/src/cascadedetect.cpp:1698: error: (-215) !empty() in function detectMultiScale

**Comment by davidpraise45** [comment]
I just updated the third script, it should be working right now. It was the path to the file.

**Comment by davidpraise45** [comment]
Is everything working properly for you?

**Comment by vibhavk** [comment]
working fine! Thanks a lot @davidpraise45  :-)

**Comment by davidpraise45** [comment]
Your welcome

D.k
